### ISSUE TITLE
error when i try to do anything (load dataset or save config)

### ISSUE THREAD

**Issue by Pocholo95** [toshiaki1729/dataset-tag-editor-standalone#22]
Task exception was never retrieved
future: <Task finished name='wevhivr389i_97' coro=<Queue.process_events() done, defined at E:\Tools\Stable Diffusion\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 97, 'data': ...on_hash': 'wevhivr389i'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.3/v/missing>
Traceback (most recent call last):
  File "E:\Tools\Stable Diffusion\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "E:\Tools\Stable Diffusion\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "E:\Tools\Stable Diffusion\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "E:\Tools\Stable Diffusion\dataset-tag-editor-standalone\venv\lib\site-packages\pydantic\main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 97, 'data': ...on_hash': 'wevhivr389i'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.3/v/missing

**Comment by SignalFlagZ** [comment]
I had the same issue.
I solved it by installing fastapi==0.95.2 .

Thanks for the useful tool.

**Comment by toshiaki1729** [comment]
I've updated gradio to 4.28.3 in >= ver0.0.6.
Version related issue may be solved.
I'm grad if you can check it.
