### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by ride5k** [toshiaki1729/dataset-tag-editor-standalone#3]
disclaimer: i am no python programmer, just a noob stumbling along.  any help appreciated!

windows AMD user (directml)

cloned repo:
git clone https://github.com/toshiaki1729/dataset-tag-editor-standalone.git

installed via CLI:
python -m venv --system-site-packages venv
.\venv\Scripts\activate
pip install -r requirements.txt

launch_user.bat:
venv "T:\tageditor\dataset-tag-editor-standalone\venv\Scripts\Python.exe"
Traceback (most recent call last):
  File "T:\tageditor\dataset-tag-editor-standalone\scripts\launch.py", line 12, in <module>
    import gradio as gr
  File "T:\tageditor\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "T:\tageditor\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\components.py", line 22, in <module>
    import matplotlib.figure
  File "T:\tageditor\dataset-tag-editor-standalone\venv\lib\site-packages\matplotlib\__init__.py", line 148, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "T:\tageditor\dataset-tag-editor-standalone\venv\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "T:\tageditor\dataset-tag-editor-standalone\venv\lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by ride5k** [comment]
T:\tageditor\dataset-tag-editor-standalone>.\venv\Scripts\activate

(venv) T:\tageditor\dataset-tag-editor-standalone>pip install pillow
Requirement already satisfied: pillow in c:\users\XXXXXXX\appdata\local\programs\python\python310\lib\site-packages (9.4.0)

however, same result as above

**Comment by toshiaki1729** [comment]
I'm not sure but re-creating venv without `--system-site-packages` option can fix, maybe . It increases storage size though.
You may need PyTorch installed in the venv.

**Comment by toshiaki1729** [comment]
or the issue is caused by the bat file?
i changed it to simply call activate bat file in the latest commit

**Comment by Vigilence** [comment]
I would delete the entire folder and try cloning it again, this is what fixed my issue.
