### ISSUE TITLE
Clear tag filters / Clear ALL filters bug

### ISSUE THREAD

**Issue by slashedstar** [toshiaki1729/dataset-tag-editor-standalone#50]
**Describe the bug**
Clear tag filters and Clear ALL filters doesn't work

**To Reproduce**
Git clone, install.bat, launch_user.bat, load a dataset, click on any tag to filter, click on Clear tag filters or Clear ALL filters, error will happen

 - OS: Microsoft Windows [Version 10.0.19045.4529]
 - Browser: Chrome 126.0.6478.127 (Official Build) (64-bit)
 - Version of this app: df8568d9184ad617ecfe5c40e2dbcd300fc0dea1

File with the complete log (from git cloning, to installation, to dataset loading and the error message): [log.txt](https://github.com/user-attachments/files/16102003/log.txt)

```
Traceback (most recent call last):
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\blocks.py", line 1847, in process_api
    result = await self.call_function(
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\blocks.py", line 1433, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\utils.py", line 788, in wrapper
    response = f(*args, **kwargs)
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\scripts\ui\tab_filter_by_tags.py", line 110, in <lambda>
    fn=lambda: self.clear_filters(update_filter_and_gallery),
TypeError: FilterByTagsUI.clear_filters() takes 1 positional argument but 2 were given
```

**Comment by toshiaki1729** [comment]
Thank you for your report!!
