### ISSUE TITLE
Error when unloading dataset

### ISSUE THREAD

**Issue by slashedstar** [toshiaki1729/dataset-tag-editor-standalone#51]
Load a dataset, click to unload: 
```
Traceback (most recent call last):
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\blocks.py", line 1847, in process_api
    result = await self.call_function(
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\blocks.py", line 1433, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\utils.py", line 788, in wrapper
    response = f(*args, **kwargs)
  File "X:\avirtual\standalonev2\dataset-tag-editor-standalone\scripts\ui\block_load_dataset.py", line 189, in unload_files
    + filter_by_tags.clear_filters(update_filter_and_gallery)
TypeError: FilterByTagsUI.clear_filters() takes 1 positional argument but 2 were given
```

**Comment by toshiaki1729** [comment]
Thank you for your report!!
