### ISSUE TITLE
ModuleNotFoundError: No module named 'print_color'

### ISSUE THREAD

**Issue by GoetheChilwell** [toshiaki1729/dataset-tag-editor-standalone#53]
please, how to deal with it, thank you so much!

Traceback (most recent call last):
  File "F:\dataset-tag-editor-standalone\scripts\launch.py", line 6, in <module>
    import cmd_args, logger
  File "F:\dataset-tag-editor-standalone\scripts\logger.py", line 1, in <module>
    from print_color import print
ModuleNotFoundError: No module named 'print_color'

**Comment by GoetheChilwell** [comment]
plus, already [install] successfully

**Comment by toshiaki1729** [comment]
Run `install.bat` and it will be fixed, I think.

**Comment by Ginnnnnnnnnnn** [comment]
I have the same problem and it doesn't work to run "install.bat". Do you solve this problem?
