### ISSUE TITLE
Got pydantic error after fresh installed

### ISSUE THREAD

**Issue by derekhsu** [toshiaki1729/dataset-tag-editor-standalone#59]
Got the following errors after freshed installed both on Linux and Windows:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 713, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 729, in simple_response
    await self.app(scope, receive, send)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 656, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 881, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/fastapi/_compat.py", line 657, in get_cached_model_fields
    return get_model_fields(model)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/fastapi/_compat.py", line 284, in get_model_fields
    return [
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/fastapi/_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/fastapi/_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 241, in __init__
    core_schema = _get_schema(type, config_wrapper, parent_depth=_parent_depth + 1)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 156, in _get_schema
    schema = gen.generate_schema(type_)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 450, in generate_schema
    schema = self._generate_schema(obj)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 688, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 695, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1520, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1588, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1678, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1674, in <lambda>
    lambda source, handler: handler(source)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1569, in inner_handler
    schema = self._generate_schema(obj)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 688, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 715, in _generate_schema_inner
    return self.match_type(obj)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 798, in match_type
    return self._match_generic_type(obj, origin)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 822, in _match_generic_type
    return self._union_schema(obj)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1010, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 450, in generate_schema
    schema = self._generate_schema(obj)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 688, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 715, in _generate_schema_inner
    return self.match_type(obj)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 802, in match_type
    return self._unknown_type_schema(obj)
  File "/workspace/dataset-tag-editor-standalone/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 366, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.4/u/schema-for-unknown-type
```

**Comment by NEXTAltair** [comment]
そのエラーに関しては、FastAPIのバージョン不整合が原因。  
FastAPIの最新バージョンがGradioおよびfastapiとの兼ね合いに問題があった。

**解決策:**  
FastAPIを`0.112.4`にダウングレードすると、そのエラーは消えた。  
リンクが参考:  
[https://github.com/gradio-app/gradio/issues/9275](https://github.com/gradio-app/gradio/issues/9275)

```bash
pip install fastapi==0.112.4
```

FastAPIをダウングレードしてもGradio 4系以降はローカルファイルに直接アクセスできないんで、「**Path whitelist**」の設定が要る。これ、READMEに書いてあったんですが、見落として3時間ぐらい悩んだ。

ちなみに、インストールバッチを動かす前にPython 3.10でvenvを作成し忘れて、うちのデフォ環境のPython 3.12のvenvそれでも動いてる。

---

#### **English Version**

This error was caused by a version mismatch with FastAPI.  
The latest version of FastAPI introduced conflicts with Gradio and Pydantic.

**Solution:**  
Downgrading FastAPI to `0.112.4` resolved the issue.  
For more details, please refer to:  
[https://github.com/gradio-app/gradio/issues/9275](https://github.com/gradio-app/gradio/issues/9275)

```bash
pip install fastapi==0.112.4
```

Even after downgrading FastAPI, Gradio 4.x and later versions don’t allow direct access to local files. You’ll need to configure the **"Path whitelist"** setting. This was mentioned in the README, but I missed it and ended up spending 3 hours troubleshooting.

By the way, I initially forgot to create the virtual environment with Python 3.10 and ended up using Python 3.12. But so far, everything is working fine in my environment.

---

**Comment by fadedfragger** [comment]
> そのエラーに関しては、FastAPIのバージョン不整合が原因。 FastAPIの最新バージョンがGradioおよびfastapiとの兼ね合いに問題があった。
> 
> **解決策:** FastAPIを`0.112.4`にダウングレードすると、そのエラーは消えた。 リンクが参考: [gradio-app/gradio#9275](https://github.com/gradio-app/gradio/issues/9275)
> 
> ```shell
> pip install fastapi==0.112.4
> ```
> 
> FastAPIをダウングレードしてもGradio 4系以降はローカルファイルに直接アクセスできないんで、「**Path whitelist**」の設定が要る。これ、READMEに書いてあったんですが、見落として3時間ぐらい悩んだ。
> 
> ちなみに、インストールバッチを動かす前にPython 3.10でvenvを作成し忘れて、うちのデフォ環境のPython 3.12のvenvそれでも動いてる。
> 
> #### **English Version**
> This error was caused by a version mismatch with FastAPI. The latest version of FastAPI introduced conflicts with Gradio and Pydantic.
> 
> **Solution:** Downgrading FastAPI to `0.112.4` resolved the issue. For more details, please refer to: [gradio-app/gradio#9275](https://github.com/gradio-app/gradio/issues/9275)
> 
> ```shell
> pip install fastapi==0.112.4
> ```
> 
> Even after downgrading FastAPI, Gradio 4.x and later versions don’t allow direct access to local files. You’ll need to configure the **"Path whitelist"** setting. This was mentioned in the README, but I missed it and ended up spending 3 hours troubleshooting.
> 
> By the way, I initially forgot to create the virtual environment with Python 3.10 and ended up using Python 3.12. But so far, everything is working fine in my environment.

still not working

**Comment by naccan55** [comment]
> そのエラーに関しては、FastAPIのバージョン不整合が原因。 FastAPIの最新バージョンがGradioおよびfastapiとの兼ね合いに問題があった。
> 
> **解決策:** FastAPIを`0.112.4`にダウングレードすると、そのエラーは消えた。 リンクが参考: [gradio-app/gradio#9275](https://github.com/gradio-app/gradio/issues/9275)
> 
> ```shell
> pip install fastapi==0.112.4
> ```
> 
> FastAPIをダウングレードしてもGradio 4系以降はローカルファイルに直接アクセスできないんで、「**Path whitelist**」の設定が要る。これ、READMEに書いてあったんですが、見落として3時間ぐらい悩んだ。
> 
> ちなみに、インストールバッチを動かす前にPython 3.10でvenvを作成し忘れて、うちのデフォ環境のPython 3.12のvenvそれでも動いてる。
> #### **English Version**
> 
> This error was caused by a version mismatch with FastAPI. The latest version of FastAPI introduced conflicts with Gradio and Pydantic.
> 
> **Solution:** Downgrading FastAPI to `0.112.4` resolved the issue. For more details, please refer to: [gradio-app/gradio#9275](https://github.com/gradio-app/gradio/issues/9275)
> 
> ```shell
> pip install fastapi==0.112.4
> ```
> 
> Even after downgrading FastAPI, Gradio 4.x and later versions don’t allow direct access to local files. You’ll need to configure the **"Path whitelist"** setting. This was mentioned in the README, but I missed it and ended up spending 3 hours troubleshooting.
> 
> By the way, I initially forgot to create the virtual environment with Python 3.10 and ended up using Python 3.12. But so far, everything is working fine in my environment.

To spell this out for those less technically inclined. go into your requirements.txt file and paste `fastapi==0.112.2 ` in its own line.
Launch the install batch file. Wait for it to finish.
Launch user.
Point your whitelist in settings to your folder directory(s) where your images are located.
Enjoy.

https://github.com/gradio-app/gradio/issues/9275#issuecomment-2348194172
