### ISSUE TITLE
"Permission denied" when attempting to load dataset files

### ISSUE THREAD

**Issue by ooofest** [toshiaki1729/dataset-tag-editor-standalone#8]
Hello,
Running on Windows 10, I start launch_user.bat from an elevated command prompt, but get this error after clicking Load in the UI:

Loading dataset from D:\dataset
Total 1 files under the directory including not image files.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.30s/it]
Traceback (most recent call last):
  File "D:\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\blocks.py", line 1069, in process_api
    result = await self.call_function(
  File "D:\dataset-tag-editor-standalone\venv\lib\site-packages\gradio\blocks.py", line 878, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\dataset-tag-editor-standalone\scripts\ui\block_load_dataset.py", line 135, in load_files_from_dir
    dte_instance.load_dataset(
  File "D:\dataset-tag-editor-standalone\scripts\dataset_tag_editor\dte_logic.py", line 746, in load_dataset
    imgpaths, self.images, taglists = kohya_metadata.read(
  File "D:\dataset-tag-editor-standalone\scripts\dataset_tag_editor\kohya_finetune_metadata.py", line 58, in read
    metadata = json.loads(json_path.read_text("utf8"))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: 'D:\\dataset'

I tried changing permissions for the above directory to allow full access for any account, but the same error occurs.

It also doesn't matter where I place the dataset images - I've tried various places on my C: drive, for example.

Ideas welcome, thanks.

**Comment by ooofest** [comment]
Think I found the problem: the pathname requires an ending backslash to load properly.
